# Generated by Django 3.2.7 on 2021-11-23 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0003_agency_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='zone',
        ),
        migrations.AddField(
            model_name='zone',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zones.agency'),
        ),
    ]
