# Generated by Django 3.2.7 on 2021-11-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0004_auto_20211123_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='agency',
        ),
        migrations.AddField(
            model_name='zone',
            name='agency',
            field=models.ManyToManyField(to='zones.Agency'),
        ),
    ]
