# Generated by Django 3.2.7 on 2021-11-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0005_auto_20211123_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['agency'], 'verbose_name_plural': 'agencies'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['zone']},
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('technician', 'Technician')], default='technician', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_technician',
            field=models.BooleanField(default=False),
        ),
    ]
