# Generated by Django 3.2.7 on 2021-11-23 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0006_auto_20211123_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='tech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='techs', to=settings.AUTH_USER_MODEL),
        ),
    ]
